# Change these first
owner: essels # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: AMP KIA BE
    url: https://accessoires-kia.be
  - name: AMP KIA LU
    url: https://accessoires-kia.lu
  - name: MAKHZAN
    url: https://makhzan.org



status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Essels Status Page
  introTitle: "**ESSELS** Status page keeps an eye on important websites"
  introMessage: This is a status page uses **real-time** data from our [GitHub repository](https://github.com/essels/uptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/essels/uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
